### ISSUE TITLE
Serving of the images not working properly

### ISSUE THREAD

**Issue by sajadghawami** [ztomm/express-responsive-images#3]
Hey,

thanks for the great library.

I ve got a problem with serving the right images:

```js

// use it before declaring static routes
app.use(
  responsiveImages({
    debug: true,
    // options
    staticDir: '/upload',
    watchedDirectories: ['/upload/sellerProductImage'],
    directScaling: true,
    directScaleSizes: [200, 400],
  })
);

// sellerProductImages
const sellerProductUploadDirectory = path.join(__dirname, '../upload/sellerProductImage');
app.use('/upload/sellerProductImage', express.static(sellerProductUploadDirectory));

```

I can see that different sizes are generated, but the normal (not rescaled) images are being served, and i get the following in the log:

```
node_1      | express-responsive-images: (test.jpg) requested directory is in watchlist: /upload/sellerProductImage
node_1      | express-responsive-images: (test.jpg) requested file: test.jpg
node_1      | express-responsive-images: (test.jpg) filetype is supported: jpg
node_1      | express-responsive-images: (test.jpg) origin image does not exists
```

When i remove the `staticDir` in the configuration above, i get the following in the log:

```
node_1      | express-responsive-images: (test.jpg) requested directory is in watchlist: /upload/sellerProductImage
node_1      | express-responsive-images: (test.jpg) requested file: test.jpg
node_1      | express-responsive-images: (test.jpg) filetype is supported: jpg
node_1      | express-responsive-images: (test.jpg) cookie "screen" is set: density=2, width=320
node_1      | express-responsive-images: (test.jpg) new image width is probably 640
node_1      | express-responsive-images: (test.jpg) origin image is smaller than new image width
node_1      | GET /upload/sellerProductImage/test.jpg 200 34.391 ms - 22759
```

But when i do that, i dont get any image served at all in the browser - which is really odd.

Any help would be much appreciated!

Thanks.

**Comment by ztomm** [comment]
Please try the following two steps. Perhaps the first one can fix it. 

1. Set `watchedDirectories: ['/sellerProductImage']` cause this options is already watching inside `staticDir`.

2. Are you sure about this line `const sellerProductUploadDirectory = path.join(__dirname, '../upload/sellerProductImage');`? Give it a try with this `const sellerProductUploadDirectory = path.join(__dirname, 'upload/sellerProductImage');`

The default value of `staticDir` is `/public`. So you should not delete it in your application.

**Comment by sajadghawami** [comment]
Thanks for the quick reply!

1. i changed it like this:
```js
app.use(
  responsiveImages({
    debug: true,
    // options
    // staticDir: path.join(__dirname, '../upload/sellerProductImage'),
    staticDir: '/upload',
    watchedDirectories: ['/sellerProductImage'],
    directScaling: true,
    directScaleSizes: [200, 400],
  })
);

```
and now i am getting:

```
node_1      | express-responsive-images: (test.jpg) requested directory is not in watchlist: /upload/sellerProductImage
```

2. pretty sure that it's right like that, because i can see images like i described above with the first configuration. This is my folder-structure:

![Bildschirmfoto 2020-09-19 um 00 21 31](https://user-images.githubusercontent.com/11796944/93650188-20808080-fa0e-11ea-9bcf-141f3ecc6bee.png)

the code i am showing is located in `app.ts`

**Comment by ztomm** [comment]
Since this is more a misconfiguration and not an issue by the module your question is related to stackoverflow. Please post your question there. I would be pleased to help you on SO.
