### ISSUE TITLE
Animation does not play when direct scaling is enabled

### ISSUE THREAD

**Issue by ServOKio** [ztomm/express-responsive-images#4]
Version: 1.2.0
# Steps To Reproduce
```js
app.use(
    responsiveImages({
        fileTypes: ['webp', 'gif'],
        breakpoints: [240],
        directScaling: true,
        directScaleSizes: [240],
    })
);
```
# The expected behavior and investigation
For example, if you try to get an image at "../3996732987026161664.gif?w=240" you will get a static image. I know that you use "sharp" to change the image size, but by default it doesn't support gif animation. They don't play in Chrome, Mozilla Developer Edition, or Yandex.

> ../3996732987026161664.gif
![3996732987026161664 (1)](https://user-images.githubusercontent.com/51263003/93722628-ee535800-fba0-11ea-8da7-71998f2bd148.gif)

> ../3996732987026161664.gif?w=240
![3996732987026161664](https://user-images.githubusercontent.com/51263003/93722613-c4019a80-fba0-11ea-872d-b600f7a93a64.gif)

**+ in addition, when the first request is made when the modified image is not yet available, the server will output the "original image" without resizing, and then after resetting the browser cache, it will output the modified image. This is an additional problem**

Yes, the client can install "libvips" dependencies and if so, you can check by reading "package.json" where can you check whether the build is installed or not:

```json
{
  "name": "server",
  "config": {
    "libvips": "8.10.1"
  }
}
```

If you want to change the gif size using "sharp" you need to specify "pageheight" = height of the GIF frame after resizing.
For example, this code will return an unframing for you that can be resized and put back together as a gif:
```js
sharp(`./input.gif`, {
    animated: true
}) .resize(100).toFile(`./out.png`, (err, info) => {
    console.log(err ? 'Error' : 'Done');
});
```
> https://user-images.githubusercontent.com/51263003/93723246-b7337580-fba5-11ea-9b55-837487890908.png

To change the size of gif and webp I used this:
```js
const image = sharp(`./input.gif`);

image.metadata().then(metadata => {
    if (metadata.pages > 1) { // if animated
        sharp(`./input.gif`, {
            animated: true // read all frames, not just one
        })
        .resize(metadata.width - 30) // for example, -30px
        .gif({ // creating a GIF from a decoded image
            loop: 0,
            pageHeight: metadata.height - 30, // set frame height - 30px
            delay: metadata.delay
        })
        .toFile(`./out.gif`, (err, info) => {
            console.log(err ? 'Error' : 'Done');
        });

    } else { // if non animated
        image
        .resize(metadata.width - 30) // for example, -30px
        .toFile(`./out.gif`, (err, info) => {
            console.log(err ? 'Error' : 'Done');
        });
    }
});
```

**Comment by ztomm** [comment]
> ... the client can install "libvips" dependencies ...

That is one point why the decision felled on sharp as image processor. With sharp it's easy to get this package installed and running (almost) out of the box. The downside is the missing feature to scale animated gifs too.

Thanks a lot for your code examples. I tested and checked some possibilities on them, but the dependency libvips stopped me finally developing in this direction.

I will mention that limitation in the readme soon.
