### ISSUE TITLE
directScaling not working in my code

### ISSUE THREAD

**Issue by ajaykumarparashar11** [ztomm/express-responsive-images#6]
I have implemented this as per documentation but directScaling is not working. is there any code i need to write for this ?

**Comment by ztomm** [comment]
Please provide some code.

**Comment by ajaykumarparashar11** [comment]
![Screenshot 2021-10-14 at 12 25 31 PM](https://user-images.githubusercontent.com/23501197/137266890-c7713084-885f-4ace-9ab0-7c5295772891.png)

code in app.js file

const responsiveImages = require('express-responsive-images');

app.use(responsiveImages({
    staticDir: '/public',
    watchedDirectories: ['/images', '/images/*'],
    fileTypes: ['webp', 'jpg', 'jpeg', 'png', 'gif'],
    fileTypeConversion: '',
    cacheSuffix: '-cache',
    cookieName: 'screen',
    scaleBy: 'breakpoint',
    breakpoints: [320, 480, 640, 800, 1024, 1280, 1366, 1440, 1600, 1920, 2048, 2560, 3440, 4096],
    directScaling: true,
    directScalingParam: 'size',
    directScaleSizes: [],
    debug: true,
}));

localhost:8081/public/images/uploads/my-image.jpg?size=100

we are using these apis for mobile apps

**Comment by ztomm** [comment]
Watch the order. Register the module before static routes.

Described here: [https://github.com/xkmgt/express-responsive-images#backend](https://github.com/xkmgt/express-responsive-images#backend)

**Comment by ajaykumarparashar11** [comment]
oh, my bad.

i did this and get a new problem

**_"no cookie in requested headers"_**

as i  am using for **mobile app APIs** and my url looks like this

**http://localhost: 8081/images/uploads/popper/popper-68163405438405420.jpg?size=100**

**Comment by ztomm** [comment]
Check the new version 1.4. 

`directScaling` is independent of cookies now.

**Comment by ajaykumarparashar11** [comment]
i have updated to the new version and still not getting the responsive image in the result. Maybe i am doing something wrong.

here i am posting latest code 
![Screenshot 2021-10-14 at 10 35 33 PM](https://user-images.githubusercontent.com/23501197/137364403-209bbf39-5b08-4b4d-90e3-ff032cf616c2.png)

here i am getting something while including the package into the file(as you can see 3 dots in above screenshot)

![Screenshot 2021-10-14 at 10 36 03 PM](https://user-images.githubusercontent.com/23501197/137364524-06aef869-bb9c-45d2-b780-662340260b41.png)

Did as per your given example on github

**Comment by ajaykumarparashar11** [comment]
i did some googling and find that your package is missing _**type information**_
Kindly check, maybe i am wrong

**Comment by ztomm** [comment]
Still wrong order in your code: [https://github.com/xkmgt/express-responsive-images/issues/6#issuecomment-943174151](https://github.com/xkmgt/express-responsive-images/issues/6#issuecomment-943174151)
