### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by ServOKio** [ztomm/express-responsive-images#7]
version: *1.5.1*

```sh
/assets/img/avatars/53423452345/4173629452741234.png
TypeError: Cannot read property 'length' of null
   at /home/main/epicworld/server/node_modules/express-responsive-images/index.js:209:24
```

209:
```js
if (deviceParameters.length) {
```

**Comment by ztomm** [comment]
The error occurs when the cookie is not sent correctly. See if you can fix this in the [frontend](https://github.com/ztomm/express-responsive-images#usage) or maybe you changed the [cookie name](https://github.com/ztomm/express-responsive-images#cookiename-string). 

I have published an update where this error is caught.
