### ISSUE TITLE
Direct scaling through google lighthouse

### ISSUE THREAD

**Issue by ServOKio** [ztomm/express-responsive-images#8]
I am creating an application on React that is displayed on `localhost` and I get files from a site with a domain, but I can't pass the google lighthouse test because cookies don't work for `localhost`. What can I do?

from `localhost` in test
![2022-03-25_05-23](https://user-images.githubusercontent.com/51263003/160042473-3db360b7-3a21-4f5a-896c-bdd78542858a.png)
and if directly in site
![2022-03-25_05-23_1](https://user-images.githubusercontent.com/51263003/160042517-2b1ade04-86eb-4f64-a251-13381f190bd1.png)

```js
app.use(
    responsiveImages({
        staticDir: '../public_html/',
        fileTypes: ['webp', 'jpg', 'jpeg', 'png'],
        watchedDirectories: ['/assets/*'],
        breakpoints: [16, 32, 64, 128, 240, 320, 480, 640, 800, 1024, 1280, 1366, 1440, 1600, 1920, 2048, 2560, 3440, 4096],
        directScaling: true,
        directScaleSizes: [16, 32, 42, 64, 128, 240, 360, 1024],
        debug: false
    })
);
```

**Comment by ztomm** [comment]
Ok. I understand. But this is not a problem of this module. The concept to determine the image sizes automatically is by transmitting the screen size with a cookie. If there is an alternative to determine the screen size, let me know.

For `directScaling` it doesn't need cookies and that seems to work for you. I think lighthouse is complaining about compression. To save even more, you could set `fileTypeConversion: 'webp'`. These file sizes should be smaller than from png. (The `directScaleSizes` don't have to be listed in `breakpoints`).

What does the transferred value (next to resources) in the browser console say? This is the more important of the two.

Please let me know if this config helps:

```javascript
app.use(
    responsiveImages({
        staticDir: '../public_html/',
        watchedDirectories: ['/assets/*'],
        fileTypeConversion: 'webp',
        directScaling: true,
        directScaleSizes: [16, 32, 42, 64, 128, 240, 360, 1024],
        debug: false
    })
);
```

Set debug to true. What is the console output?

**Comment by ServOKio** [comment]
> Set debug to true. What is the console output?

![2022-03-25_11-34_1](https://user-images.githubusercontent.com/51263003/160084505-69121c7d-266d-4f25-ae38-79cf619c2448.png)

![2022-03-25_11-36](https://user-images.githubusercontent.com/51263003/160085029-772af808-bdc1-4d65-9794-3652e7f2dbed.png)

**Comment by ztomm** [comment]
Have you set `fileTypeConversion: 'webp'`?

**Comment by ServOKio** [comment]
Yes

**Comment by ztomm** [comment]
Sorry, I can't help you with your Lighthouse problem.

**Comment by ServOKio** [comment]
Maybe it's worth adding an option to ignore device parameters ? For example, in the absence of `deviceParameters[2]` set a parameter from the configuration (let's say 1) and the size will be set to `requestQueryW` 
```js
newImageWidth = Math.round(requestQueryW * 1) //🤷‍♀️
```

**Comment by ztomm** [comment]
I'll take a quick look. Give me a moment.

**Comment by ztomm** [comment]
Made an update. Please give me feedback to 

`"express-responsive-images": "^1.5.5"`

**Comment by ServOKio** [comment]
```log
express-responsive-images: (1843537935581214.png) requested directory is in watchlist: /assets/img/avatars/3549530931200
express-responsive-images: (1843537935581214.png) requested file: 1843537935581214.png
express-responsive-images: (1843537935581214.png) filetype is supported: png
express-responsive-images: (1843537935581214.png) no cookie in headers
express-responsive-images: (1843537935581214.png) no cookies sent but directScaling is active
express-responsive-images: (1843537935581214.png) new image width is probably 32
TypeError: Cannot read property 'toLowerCase' of undefined
    at /home/main/root/servokio.net/server/node_modules/express-responsive-images/index.js:252:68
    at Layer.handle [as handle_request] (/home/main/root/servokio.net/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/main/root/servokio.net/server/node_modules/express/lib/router/index.js:323:13)
    at /home/main/root/servokio.net/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/main/root/servokio.net/server/node_modules/express/lib/router/index.js:341:12)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/index.js:275:10)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:127:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    at next (/home/main/root/servokio.net/server/node_modules/express/lib/router/route.js:131:14)
    ```

**Comment by ztomm** [comment]
Are you still testing with lighthouse?

**Comment by ServOKio** [comment]
Yes

**Comment by ztomm** [comment]
Fix for lighthouse: `"express-responsive-images": "^1.5.7"`
