### ISSUE TITLE
Race Conditions depending environment?

### ISSUE THREAD

**Issue by koen-bosmans** [ztomm/express-responsive-images#9]
At first I didn't notice it on my local computer, which runs fast and free in development. But as soon, as I implemented it (correctly) on a shared host, troubles began.
Images aren't always scaled, but end op zero byte. Or aren't added to the proper cache folder. 

At first I tought it was me. In fact I added the static middleware to the express, but didn't allow access to the cache folder. Instead I re-routed any request to a cached file myselfn re-checking its existence. 

After reverting to dictated procedures as in the demo, the problem didn't seem to resolve. 

Altering createCacheFile() (l 125), adding async/await to Sharp processing, seems to resolve the zero byte images. Still sometimes the expected cache folder isn't properly created. 

If I do find the time, I'm happy do some testing.  I find this module a very nice add-on.

```
		// create scaled image
		var createCacheFile = () => {
			// create directory if needed
			fs.ensureDir(cacheDirPath, async err => {
				if (err) {
					debug(`red`, `(${reqFileName}) failed to create caching directory: ${cacheFilePath}`)
					return next()
				}
				// disable sharp to cache files
				sharp.cache(false)
				// create and cache image
				try {
					await sharp(originFilePath)
						.resize(cacheFileWidth)
						.withMetadata()
						.toFile(cacheFilePath);
				} catch(err) {
					debug(`red`, `(${reqFileName}) sharp faild to create file: ${err}`)
					return next()
				}
				debug(`green`, `(${reqFileName}) image scaled and created: ${cacheFilePath}`)
				return sendCachedFile()
			})
		}
```

**Comment by ztomm** [comment]
It really makes sense to run that in sync at that point. I have adopted your suggestion in version 1.6.0. Would be great if you have the time to test it again and leave a feedback. Thanks.
